#!/usr/bin/env python3
"""
SKU场景数据扩展 - 从111扩展到500+ SKU
覆盖多个行业：3C数码、快消、保健品、家居等
"""

import json
from datetime import datetime

# 场景模板库（50个通用场景）
SCENARIO_TEMPLATES = [
    {"name": "新年礼物", "pain_point": "新年不知道送什么礼物", "resonance": "想要送出有新年祝福意义的礼物", "content_angles": ["新年礼物推荐", "过年送礼清单", "新年好物"], "hot_topics": ["新年", "过年", "新年礼物", "跨年"]},
    {"name": "情人节限定", "pain_point": "情人节想送特别的礼物", "resonance": "想要独一无二的节日礼物", "content_angles": ["情人节礼物推荐", "节日特别款", "浪漫礼盒"], "hot_topics": ["情人节", "限定", "520", "七夕"]},
    {"name": "七夕特别", "pain_point": "七夕想送有中国特色的礼物", "resonance": "想要有传统文化底蕴的礼物", "content_angles": ["七夕礼物推荐", "中国式浪漫", "传统节日好物"], "hot_topics": ["七夕", "中国情人节", "传统文化", "牛郎织女"]},
    {"name": "圣诞节礼物", "pain_point": "圣诞节不知道送什么", "resonance": "想要有节日氛围的礼物", "content_angles": ["圣诞礼物推荐", "圣诞限定好物", "节日氛围布置"], "hot_topics": ["圣诞节", "圣诞礼物", "平安夜", "跨年"]},
    {"name": "女神节专属", "pain_point": "三八节不知道送什么", "resonance": "想要送女性专属好物", "content_angles": ["女神节礼物", "女性专属推荐", "女王节好物"], "hot_topics": ["女神节", "三八节", "女王节", "女性礼物"]},
    {"name": "母亲节礼物", "pain_point": "母亲节不知道送什么", "resonance": "想送妈妈有意义又实用的礼物", "content_angles": ["母亲节礼物推荐", "送妈妈什么好", "感恩母亲"], "hot_topics": ["母亲节", "送妈妈", "妈妈礼物", "感恩"]},
    {"name": "父亲节礼物", "pain_point": "父亲节不知道送什么", "resonance": "想送爸爸实用又有品质的礼物", "content_angles": ["父亲节礼物推荐", "送爸爸什么好", "老爸的心意"], "hot_topics": ["父亲节", "送爸爸", "爸爸礼物", "父爱"]},
    {"name": "儿童节礼物", "pain_point": "儿童节不知道送孩子什么", "resonance": "想送孩子喜欢又有意义的礼物", "content_angles": ["儿童节礼物推荐", "孩子喜欢的礼物", "六一礼物清单"], "hot_topics": ["儿童节", "六一", "孩子礼物", "亲子"]},
    {"name": "教师节礼物", "pain_point": "教师节不知道送老师什么", "resonance": "想要表达感谢又不失礼貌", "content_angles": ["教师节礼物推荐", "送老师什么好", "尊师重道好物"], "hot_topics": ["教师节", "送老师", "感恩老师", "老师礼物"]},
    {"name": "中秋送礼", "pain_point": "中秋节送礼选择困难", "resonance": "想要有中秋元素的礼物", "content_angles": ["中秋礼盒推荐", "月饼搭配好物", "团圆节送礼"], "hot_topics": ["中秋节", "月饼", "团圆", "中秋礼盒"]},
    {"name": "春节年货", "pain_point": "过年不知道买什么年货", "resonance": "想要有年味又实用的年货", "content_angles": ["年货清单推荐", "过年必备好物", "年味满满"], "hot_topics": ["春节", "年货", "过年", "新年好物"]},
    {"name": "生日惊喜", "pain_point": "朋友/对象生日不知道送什么", "resonance": "想送出有新意又实用的礼物", "content_angles": ["生日礼物创意推荐", "投其所好的礼物选择", "仪式感礼物推荐"], "hot_topics": ["生日礼物", "惊喜礼物", "仪式感", "创意礼物"]},
    {"name": "毕业礼物", "pain_point": "同学朋友毕业不知道送什么", "resonance": "想要送出有纪念意义的毕业礼物", "content_angles": ["毕业礼物清单", "同学礼物推荐", "有纪念意义的好物"], "hot_topics": ["毕业", "同学礼物", "毕业季", "升学"]},
    {"name": "乔迁新居", "pain_point": "搬新家不知道买什么", "resonance": "想要打造温馨舒适的新家", "content_angles": ["新家必备清单", "搬家好物推荐", "入住必备神器"], "hot_topics": ["乔迁之喜", "新家布置", "搬家清单", "入住好物"]},
    {"name": "新婚礼物", "pain_point": "朋友结婚不知道送什么", "resonance": "想送实用又有心意的新婚礼物", "content_angles": ["新婚礼物推荐", "结婚好物分享", "新婚祝福礼"], "hot_topics": ["新婚礼物", "结婚好物", "新婚祝福", "婚礼礼物"]},
    {"name": "宝宝出生", "pain_point": "朋友生宝宝不知道送什么", "resonance": "想送实用又安全的母婴礼物", "content_angles": ["新生儿礼物推荐", "满月礼物清单", "母婴好物分享"], "hot_topics": ["新生儿礼物", "满月礼", "宝宝礼物", "母婴好物"]},
    {"name": "升职加薪", "pain_point": "升职了想犒劳自己", "resonance": "想要奖励自己更有品质的生活", "content_angles": ["升职奖励自己", "职场进阶好物", "品质生活分享"], "hot_topics": ["升职", "加薪", "犒劳自己", "职场好物"]},
    {"name": "日常通勤", "pain_point": "每天通勤需要实用好物", "resonance": "想要提升通勤体验", "content_angles": ["通勤必备好物", "上班族推荐", "日常实用清单"], "hot_topics": ["通勤", "上班族", "日常好物", "实用推荐"]},
    {"name": "居家办公", "pain_point": "在家办公需要好装备", "resonance": "想要提升居家办公效率", "content_angles": ["居家办公装备", "WFH好物推荐", "远程办公神器"], "hot_topics": ["居家办公", "WFH", "远程办公", "在家工作"]},
    {"name": "运动健身", "pain_point": "想培养运动习惯", "resonance": "想要适合新手的运动装备", "content_angles": ["健身入门装备", "运动好物推荐", "运动打卡分享"], "hot_topics": ["健身", "运动", "减肥", "健康生活"]},
    {"name": "旅行出游", "pain_point": "旅行不知道带什么", "resonance": "想要旅行必备好物", "content_angles": ["旅行好物清单", "出游必备神器", "旅行装备分享"], "hot_topics": ["旅行", "出游", "旅行好物", "出行必备"]},
    {"name": "宅家必备", "pain_point": "喜欢宅家但想提升生活品质", "resonance": "想要让宅家生活更舒适", "content_angles": ["宅家好物推荐", "居家生活神器", "幸福感提升"], "hot_topics": ["宅家", "居家好物", "生活品质", "幸福感"]},
    {"name": "夜猫子必备", "pain_point": "经常熬夜需要护肝护肤", "resonance": "想要减少熬夜伤害", "content_angles": ["熬夜党必备", "护肝养颜好物", "熬夜补救方案"], "hot_topics": ["熬夜", "护肝", "护肤", "养生"]},
    {"sku_name": "学生党必备", "pain_point": "学生预算有限需要高性价比", "resonance": "想要在有限预算内买最实用的", "content_angles": ["学生党必买清单", "宿舍好物推荐", "性价比最高的平替"], "hot_topics": ["学生党", "宿舍好物", "开学必备", "平价好物"]},
    {"name": "租房一族", "pain_point": "租房想布置但怕浪费", "resonance": "想要便宜又好用的租房好物", "content_angles": ["租房好物推荐", "出租屋改造", "搬家必带清单"], "hot_topics": ["租房", "出租屋", "搬家好物", "租房改造"]},
    {"name": "养宠家庭", "pain_point": "养宠物需要好物", "resonance": "想要让宠物更舒适健康", "content_angles": ["宠物好物推荐", "养猫狗必备", "宠物用品测评"], "hot_topics": ["养宠", "宠物好物", "猫咪", "狗狗"]},
    {"name": "宝爸宝妈", "pain_point": "带娃需要实用好物", "resonance": "想要让带娃更轻松", "content_angles": ["带娃好物分享", "育儿神器推荐", "新手爸妈必看"], "hot_topics": ["带娃", "育儿", "新手爸妈", "母婴好物"]},
    {"name": "独居生活", "pain_point": "独居需要安全便利好物", "resonance": "想要独居生活更安心", "content_angles": ["独居好物推荐", "一人居必备", "独居安全清单"], "hot_topics": ["独居", "一人居", "独居好物", "安全生活"]},
    {"name": "情侣日常", "pain_point": "情侣想一起用好玩的东西", "resonance": "想要增进感情的好物", "content_angles": ["情侣好物分享", "恋爱必备", "甜蜜日常"], "hot_topics": ["情侣", "恋爱", "情侣好物", "甜蜜日常"]},
    {"name": "性价比之选", "pain_point": "预算有限想买最值的产品", "resonance": "想要花最少的钱买最值的东西", "content_angles": ["同价位最值得买的一款", "平价替代方案", "什么时候买最划算"], "hot_topics": ["性价比", "平价好物", "省钱攻略", "必买清单"]},
    {"name": "真实自用分享", "pain_point": "网上种草太多不知道哪个真正好用", "resonance": "想要真实的用户体验", "content_angles": ["真实使用一个月后的感受", "网上不会告诉你的细节", "和同类产品对比真实体验"], "hot_topics": ["自用分享", "真实测评", "踩坑经历", "真实推荐"]},
    {"name": "避坑指南", "pain_point": "担心买到踩坑产品", "resonance": "想要避开智商税产品", "content_angles": ["同类产品避坑指南", "选购要点总结", "常见选购误区"], "hot_topics": ["避坑指南", "智商税", "选购指南", "避雷"]},
    {"name": "深度测评", "pain_point": "想了解产品真实性能", "resonance": "想要专业详尽的产品分析", "content_angles": ["专业维度深度测评", "实验室数据对比", "真实数据说话"], "hot_topics": ["深度测评", "专业测评", "数据对比", "横评"]},
    {"name": "开箱体验", "pain_point": "想了解产品开箱第一印象", "resonance": "想要看到真实的产品细节", "content_angles": ["惊喜开箱分享", "第一眼感受", "包装细节展示"], "hot_topics": ["开箱", "开箱测评", "新品开箱", "开箱分享"]},
    {"name": "好物推荐", "pain_point": "想找值得买的好物", "resonance": "想要不踩雷的购买建议", "content_angles": ["真心推荐的好物", "回购率超高的单品", "用过都说好的产品"], "hot_topics": ["好物推荐", "必买清单", "回购好物", "真心推荐"]},
    {"name": "省钱攻略", "pain_point": "想省钱买好东西", "resonance": "想要最优惠的购买渠道", "content_angles": ["省钱购买技巧", "优惠券攻略", "最低价入手时间"], "hot_topics": ["省钱", "优惠", "攻略", "薅羊毛"]},
    {"name": "品牌对比", "pain_point": "在几个品牌间纠结", "resonance": "想了解各品牌的优缺点", "content_angles": ["品牌横向对比", "各品牌差异分析", "选购建议"], "hot_topics": ["对比", "品牌对比", "横评", "选购"]},
    {"name": "新手入门", "pain_point": "刚接触这类产品不知道怎么选", "resonance": "想要新手友好的入门推荐", "content_angles": ["新手入门指南", "小白必看选购", "从零开始推荐"], "hot_topics": ["新手", "入门", "小白必看", "新手推荐"]},
    {"name": "换季必备", "pain_point": "换季不知道买什么", "resonance": "想要应对换季的好物", "content_angles": ["换季好物清单", "季节更替必备", "换季护肤攻略"], "hot_topics": ["换季", "季节", "春夏必备", "秋冬好物"]},
    {"name": "夏季清凉", "pain_point": "夏天太热想要清凉好物", "resonance": "想要夏天降温神器", "content_angles": ["夏季清凉好物", "避暑神器推荐", "夏天必备清单"], "hot_topics": ["夏天", "清凉", "避暑", "夏日好物"]},
    {"name": "冬季保暖", "pain_point": "冬天太冷想要保暖好物", "resonance": "想要冬天取暖神器", "content_angles": ["冬季保暖好物", "取暖神器推荐", "过冬必备清单"], "hot_topics": ["冬天", "保暖", "取暖", "过冬好物"]},
    {"name": "开学季", "pain_point": "开学不知道买什么", "resonance": "想要开学必备好物", "content_angles": ["开学必备清单", "学生党开学好物", "新学期装备"], "hot_topics": ["开学", "学生党", "开学季", "新学期"]},
    {"name": "双11攻略", "pain_point": "双11不知道买什么最划算", "resonance": "想要双11凑单好物", "content_angles": ["双11必买清单", "双十一凑单攻略", "大促省钱指南"], "hot_topics": ["双11", "双十一", "大促", "购物节"]},
    {"name": "618攻略", "pain_point": "618不知道买什么最划算", "resonance": "想要618凑单好物", "content_angles": ["618必买清单", "年中大促攻略", "618省钱指南"], "hot_topics": ["618", "年中大促", "购物节", "省钱攻略"]},
    {"name": "送礼面子足", "pain_point": "想送礼有面子但预算有限", "resonance": "想送看起来高端但不贵的礼物", "content_angles": ["送礼有面子推荐", "小预算大面子", "送礼不踩雷"], "hot_topics": ["送礼", "面子", "高端礼物", "送礼攻略"]},
    {"name": "闺蜜分享", "pain_point": "想和闺蜜分享好物", "resonance": "想要闺蜜一起用的好东西", "content_angles": ["闺蜜同款好物", "姐妹一起入坑", "闺蜜礼物推荐"], "hot_topics": ["闺蜜", "姐妹", "闺蜜同款", "姐妹好物"]},
    {"name": "情侣同款", "pain_point": "想和对象用情侣款", "resonance": "想要情侣一起用好物", "content_angles": ["情侣同款推荐", "情侣必备好物", "甜蜜同款分享"], "hot_topics": ["情侣同款", "情侣好物", "甜蜜日常", "情侣必备"]},
    {"name": "父母孝心", "pain_point": "想给父母买好东西", "resonance": "想要实用又能表达孝心的礼物", "content_angles": ["送父母好物推荐", "孝心礼物清单", "爸妈喜欢的好物"], "hot_topics": ["送父母", "孝心", "父母礼物", "孝敬长辈"]},
    {"name": "领导送礼", "pain_point": "想送领导得体的礼物", "resonance": "想要正式又有品质的商务礼物", "content_angles": ["送领导礼物推荐", "商务礼品指南", "体面送礼"], "hot_topics": ["送领导", "商务送礼", "职场礼物", "正式场合"]},
]

# 新增SKU数据 - 按行业分类
NEW_SKUS = {
    "3C数码": [
        {"sku_name": "MacBook Pro 14", "brand": "苹果", "specs": "M3 Pro/18GB/512GB", "selling_points": ["M3 Pro芯片", "Liquid Retina XDR", "22小时续航", "专业级性能"]},
        {"sku_name": "iPad Pro 12.9", "brand": "苹果", "specs": "M2芯片/256GB", "selling_points": ["M2芯片", "mini-LED屏幕", "Apple Pencil支持", "专业创作"]},
        {"sku_name": "AirPods Pro 2", "brand": "苹果", "specs": "H2芯片/主动降噪", "selling_points": ["主动降噪", "空间音频", "自适应通透", "USB-C充电"]},
        {"sku_name": "Apple Watch Ultra 2", "brand": "苹果", "specs": "49mm/钛金属", "selling_points": ["双频GPS", "100米防水", "36小时续航", "极限运动"]},
        {"sku_name": "华为MatePad Pro", "brand": "华为", "specs": "麒麟9000W/12GB+256GB", "selling_points": ["OLED屏幕", "M-Pencil支持", "鸿蒙系统", "多屏协同"]},
        {"sku_name": "华为FreeBuds Pro 3", "brand": "华为", "specs": "麒麟A2芯片", "selling_points": ["星闪技术", "智慧降噪", "空间音频", "无损音质"]},
        {"sku_name": "华为WATCH GT 4", "brand": "华为", "specs": "46mm/14天续航", "selling_points": ["科学运动", "健康管理", "蓝牙通话", "超长续航"]},
        {"sku_name": "小米平板6 Pro", "brand": "小米", "specs": "骁龙8+/12GB+256GB", "selling_points": ["2.8K屏幕", "144Hz刷新率", "四扬声器", "快充"]},
        {"sku_name": "小米手环8 Pro", "brand": "小米", "specs": "1.74英寸AMOLED", "selling_points": ["大屏显示", "150+运动模式", "独立GPS", "14天续航"]},
        {"sku_name": "小米Buds 4 Pro", "brand": "小米", "specs": "48dB降噪", "selling_points": ["空间音频", "独立空间音频", "Hi-Res音质", "无线充电"]},
        {"sku_name": "索尼WH-1000XM5", "brand": "索尼", "specs": "主动降噪/30小时续航", "selling_points": ["业界最强降噪", "30小时续航", "AI降噪", "高解析音质"]},
        {"sku_name": "索尼WF-1000XM5", "brand": "索尼", "specs": "真无线/降噪", "selling_points": ["双芯片降噪", "LDAC音质", "IPX4防水", "小巧轻便"]},
        {"sku_name": "BOSE QuietComfort Ultra", "brand": "BOSE", "specs": "沉浸式音频/降噪", "selling_points": ["沉浸式空间音频", "CustomTune技术", "24小时续航", "舒适佩戴"]},
        {"sku_name": "戴尔XPS 15", "brand": "戴尔", "specs": "i7-13700H/32GB/1TB", "selling_points": ["4K OLED屏", "CNC铝机身", "InfinityEdge", "创作利器"]},
        {"sku_name": "联想ThinkPad X1 Carbon", "brand": "联想", "specs": "i7-1365U/16GB/1TB", "selling_points": ["1.12kg轻薄", "军工品质", "小红点", "商务首选"]},
        {"sku_name": "华硕ROG幻16", "brand": "华硕", "specs": "i9-13900H/RTX4070", "selling_points": ["星云屏", "轻薄游戏本", "240Hz刷新", "创作游戏两不误"]},
        {"sku_name": "雷蛇黑寡妇V4", "brand": "雷蛇", "specs": "机械键盘/RGB", "selling_points": ["雷蛇绿轴", "Chroma RGB", "多媒体旋钮", "磁吸腕托"]},
        {"sku_name": "樱桃MX8.2", "brand": "CHERRY", "specs": "三模无线/铝壳", "selling_points": ["德国原厂轴", "三模连接", "铝制外壳", "87键布局"]},
        {"sku_name": "大疆Mini 4 Pro", "brand": "大疆", "specs": "4K/全向避障", "selling_points": ["全向避障", "4K 60fps", "20公里图传", "249g轻量"]},
        {"sku_name": "大疆Pocket 3", "brand": "大疆", "specs": "4K/云台相机", "selling_points": ["2英寸旋转屏", "三轴云台", "4K 120fps", "便携Vlog"]},
        {"sku_name": "GoPro HERO12", "brand": "GoPro", "specs": "5.3K/防抖", "selling_points": ["5.3K视频", "HyperSmooth6.0", "10bit色彩", "177度超广角"]},
        {"sku_name": "Insta360 X3", "brand": "Insta360", "specs": "全景相机/5.7K", "selling_points": ["5.7K全景", "隐形自拍杆", "FlowState防抖", "AI剪辑"]},
        {"sku_name": "三星Galaxy S24 Ultra", "brand": "三星", "specs": "骁龙8 Gen3/12GB+256GB", "selling_points": ["Galaxy AI", "S Pen手写", "2亿像素", "钛金属边框"]},
        {"sku_name": "三星Galaxy Tab S9 Ultra", "brand": "三星", "specs": "14.6英寸/骁龙8 Gen2", "selling_points": ["Dynamic AMOLED", "IP68防水", "S Pen", "DeX模式"]},
        {"sku_name": "一加12", "brand": "一加", "specs": "骁龙8 Gen3/16GB+512GB", "selling_points": ["哈苏影像", "2K东方屏", "5400mAh", "100W快充"]},
        {"sku_name": "真我GT5 Pro", "brand": "真我", "specs": "骁龙8 Gen3/16GB+1TB", "selling_points": ["IMX890潜望", "5400mAh", "100W快充", "性价比之王"]},
        {"sku_name": "iQOO 12 Pro", "brand": "iQOO", "specs": "骁龙8 Gen3/16GB+512GB", "selling_points": ["电竞芯片Q1", "2K E7屏", "120W快充", "游戏旗舰"]},
        {"sku_name": "红魔9 Pro", "brand": "红魔", "specs": "骁龙8 Gen3/16GB+512GB", "selling_points": ["屏下摄像头", "主动散热风扇", "6500mAh", "游戏肩键"]},
        {"sku_name": "ROG游戏手机8", "brand": "ROG", "specs": "骁龙8 Gen3/16GB+512GB", "selling_points": ["AniMe Vision", "AirTriggers", "165Hz三星屏", "酷冷风扇"]},
        {"sku_name": "魅族21", "brand": "魅族", "specs": "骁龙8 Gen3/12GB+256GB", "selling_points": ["1.74mm极窄边", "Aicy灵动环", "Flyme 10", "超声波指纹"]},
        {"sku_name": "努比亚Z60 Ultra", "brand": "努比亚", "specs": "骁龙8 Gen3/16GB+512GB", "selling_points": ["屏下摄像", "35mm主摄", "6000mAh", "IP68"]},
        {"sku_name": "坚果N1S Pro", "brand": "坚果", "specs": "4K/三色激光", "selling_points": ["三色激光", "4K分辨率", "云台设计", "丹拿音响"]},
        {"sku_name": "极米RS10 Ultra", "brand": "极米", "specs": "4K/护眼三色激光", "selling_points": ["护眼三色激光", "全自动云台", "IMAX认证", "哈曼音响"]},
        {"sku_name": "当贝X5S", "brand": "当贝", "specs": "ALPD激光/3300CVIA", "selling_points": ["ALPD激光", "3300CVIA流明", "MT9679芯片", "360度云台"]},
        {"sku_name": "海信Vidda C1S", "brand": "海信", "specs": "4K/三色激光", "selling_points": ["三色激光", "1600CVIA", "JBL音响", "0有害蓝光"]},
        {"sku_name": "明基TK700ST", "brand": "明基", "specs": "4K/短焦/游戏", "selling_points": ["4K短焦", "240Hz高刷", "4ms低延迟", "3000流明"]},
        {"sku_name": "爱普生EF-15", "brand": "爱普生", "specs": "3LCD/激光", "selling_points": ["3LCD技术", "激光光源", "250万对比度", "5年质保"]},
        {"sku_name": "佳能EOS R6 Mark II", "brand": "佳能", "specs": "全画幅/2420万", "selling_points": ["40fps连拍", "8级防抖", "4K 60p", "深度学习对焦"]},
        {"sku_name": "索尼A7C II", "brand": "索尼", "specs": "全画幅/3300万", "selling_points": ["AI对焦芯片", "10bit 4:2:2", "7级防抖", "紧凑机身"]},
        {"sku_name": "尼康Z6 III", "brand": "尼康", "specs": "全画幅/2450万", "selling_points": ["部分堆栈CMOS", "6K RAW", "8级防抖", "120fps连拍"]},
        {"sku_name": "富士X-T5", "brand": "富士", "specs": "APS-C/4020万", "selling_points": ["胶片模拟", "7档防抖", "1/180000快门", "复古外观"]},
        {"sku_name": "理光GR IIIx", "brand": "理光", "specs": "APS-C/40mm", "selling_points": ["40mm人文焦段", "单手操作", "正片模式", "口袋机皇"]},
    ],
    "美妆护肤": [
        {"sku_name": "SK-II神仙水", "brand": "SK-II", "specs": "230ml/PITERA", "selling_points": ["90% PITERA", "改善肤质", "提亮肤色", "抗初老"]},
        {"sku_name": "雅诗兰黛小棕瓶", "brand": "雅诗兰黛", "specs": "50ml/修护精华", "selling_points": ["夜间修护", "淡化细纹", "维稳肌肤", "抗老精华"]},
        {"sku_name": "兰蔻菁纯面霜", "brand": "兰蔻", "specs": "60ml/玫瑰精粹", "selling_points": ["玻色因", "玫瑰精粹", "抗老紧致", "滋润修护"]},
        {"sku_name": "海蓝之谜精华面霜", "brand": "海蓝之谜", "specs": "60ml/神奇活性精萃", "selling_points": ["神奇活性精萃", "修护屏障", "深层滋养", "奢华护肤"]},
        {"sku_name": "赫莲娜黑绷带", "brand": "赫莲娜", "specs": "50ml/30%玻色因", "selling_points": ["30%玻色因", "修护抗老", "紧致轮廓", "夜间修护"]},
        {"sku_name": "修丽可CE精华", "brand": "修丽可", "specs": "30ml/抗氧化", "selling_points": ["15%维C", "抗氧化", "提亮肤色", "抗老防护"]},
        {"sku_name": "倩碧镭射瓶", "brand": "倩碧", "specs": "50ml/美白淡斑", "selling_points": ["CL302配方", "淡斑美白", "均匀肤色", "温和不刺激"]},
        {"sku_name": "科颜氏高保湿霜", "brand": "科颜氏", "specs": "125ml/角鲨烷", "selling_points": ["角鲨烷", "冰川保护蛋白", "深层保湿", "修复屏障"]},
        {"sku_name": "悦木之源菌菇水", "brand": "悦木之源", "specs": "200ml/灵芝精华", "selling_points": ["灵芝精华", "舒缓镇静", "祛痘消炎", "维稳肌肤"]},
        {"sku_name": "黛珂紫苏水", "brand": "黛珂", "specs": "300ml/紫苏精华", "selling_points": ["紫苏精华", "控油祛痘", "收敛毛孔", "清爽质地"]},
        {"sku_name": "奥尔滨健康水", "brand": "奥尔滨", "specs": "330ml/薏仁精华", "selling_points": ["薏仁精华", "调理角质", "控油祛痘", "日本国民水"]},
        {"sku_name": "CPB长管隔离", "brand": "CPB", "specs": "37ml/光凝润采", "selling_points": ["转油为光", "均匀肤色", "持久妆效", "养肤隔离"]},
        {"sku_name": "香缇卡隔离", "brand": "香缇卡", "specs": "50g/Just Skin", "selling_points": ["植物萃取", "轻薄自然", "养肤底妆", "伪素颜神器"]},
        {"sku_name": "YSL恒久粉底液", "brand": "YSL", "specs": "25ml/超薄雾面", "selling_points": ["超薄雾面", "24小时持妆", "控油遮瑕", "高级妆感"]},
        {"sku_name": "阿玛尼权力粉底液", "brand": "阿玛尼", "specs": "30ml/高遮瑕", "selling_points": ["高遮瑕", "16小时持妆", "控油不拔干", "专业底妆"]},
        {"sku_name": "雅诗兰黛DW粉底液", "brand": "雅诗兰黛", "specs": "30ml/油皮亲妈", "selling_points": ["油皮亲妈", "24小时不脱妆", "高遮瑕", "防水防汗"]},
        {"sku_name": "兰蔻持妆粉底液", "brand": "兰蔻", "specs": "30ml/轻薄持妆", "selling_points": ["轻薄透气", "18小时持妆", "自然妆感", "不暗沉"]},
        {"sku_name": "纪梵希四宫格散粉", "brand": "纪梵希", "specs": "12g/四色定妆", "selling_points": ["四色融合", "柔焦定妆", "控油持妆", "经典散粉"]},
        {"sku_name": "NARS大白饼", "brand": "NARS", "specs": "10g/流光肌", "selling_points": ["细腻粉质", "柔焦磨皮", "控油持妆", "透明无色"]},
        {"sku_name": "玫珂菲高清散粉", "brand": "玫珂菲", "specs": "8.5g/无痕蜜粉", "selling_points": ["无痕定妆", "控油持久", "不卡粉", "专业彩妆"]},
        {"sku_name": "MAC子弹头", "brand": "MAC", "specs": "3g/经典唇膏", "selling_points": ["丰富色号", "哑光显色", "持久不脱", "经典之选"]},
        {"sku_name": "YSL小金条", "brand": "YSL", "specs": "2.2g/细管纯口红", "selling_points": ["皮革哑光", "高定色彩", "持久显色", "奢华包装"]},
        {"sku_name": "迪奥999", "brand": "迪奥", "specs": "3.5g/正红色", "selling_points": ["经典正红", "显白提气", "滋润显色", "女王之色"]},
        {"sku_name": "阿玛尼红管", "brand": "阿玛尼", "specs": "6.5ml/丝绒唇釉", "selling_points": ["丝绒质地", "显色饱满", "持久不拔干", "高级妆感"]},
        {"sku_name": "香奈儿coco", "brand": "香奈儿", "specs": "3.5g/可可小姐", "selling_points": ["滋润显色", "经典香味", "优雅包装", "多色可选"]},
        {"sku_name": "TF黑管", "brand": "Tom Ford", "specs": "3g/黑管唇膏", "selling_points": ["奢华质地", "高显色度", "滋润持久", "高级包装"]},
        {"sku_name": "3CE丝绒唇釉", "brand": "3CE", "specs": "4g/雾面唇釉", "selling_points": ["韩系色彩", "丝绒雾面", "平价好用", "多色可选"]},
        {"sku_name": "完美日记小细跟", "brand": "完美日记", "specs": "0.8g/细管口红", "selling_points": ["国货之光", "高定质感", "显白显色", "性价比高"]},
        {"sku_name": "花西子雕花口红", "brand": "花西子", "specs": "3.2g/微雕工艺", "selling_points": ["东方美学", "微雕工艺", "滋润不干", "苗族元素"]},
        {"sku_name": "毛戈平高光膏", "brand": "毛戈平", "specs": "12g/光影塑形", "selling_points": ["中国光影", "立体轮廓", "自然提亮", "大师同款"]},
        {"sku_name": "彩棠争光气垫", "brand": "彩棠", "specs": "15g*2/国风底妆", "selling_points": ["国货底妆", "清透自然", "唐毅设计", "养肤气垫"]},
        {"sku_name": "珀莱雅红宝石精华", "brand":